-- ============================================================================
-- Sprint 7 T7 - pg_cron health tick for Solo WhatsApp instances
-- ============================================================================
--
-- PURPOSE
--   Schedule a 5-minute recurring job that calls the solo-health-check edge
--   function. The function polls every non-error wpp_instances row against
--   the whatsmiau connectionState endpoint, syncs status changes, then
--   triggers sync-instance-billing for equipes whose status changed.
--
-- DEPENDENCY CHAIN
--   1. pg_cron - enables cron.schedule()
--   2. pg_net  - enables net.http_post()
--
-- SAFETY
--   This committed migration is intentionally inert. It documents the cron job
--   definition, but it does not create extensions or register the job. Do not
--   commit Supabase service-role keys into migrations.
--
-- HOW TO ENABLE AFTER DEPLOY IS HEALTHY
--   1. Enable pg_cron and pg_net in Supabase Dashboard > Database > Extensions.
--   2. Run a separate operator-only SQL script in the SQL editor or via CLI.
--      Inject live values at execution time; do not edit this migration.
--
--   One-off enablement template:
--
--     CREATE EXTENSION IF NOT EXISTS pg_cron;
--     CREATE EXTENSION IF NOT EXISTS pg_net;
--
--     SELECT cron.unschedule('sprint7_health_tick')
--     WHERE EXISTS (
--       SELECT 1 FROM cron.job WHERE jobname = 'sprint7_health_tick'
--     );
--
--     SELECT cron.schedule(
--       'sprint7_health_tick',
--       '*/5 * * * *',
--       $$
--         SELECT net.http_post(
--           url     := 'https://<project>.supabase.co/functions/v1/solo-health-check',
--           headers := jsonb_build_object(
--                        'Content-Type',  'application/json',
--                        'x-cron-secret', '<SOLO_HEALTH_CRON_SECRET>'
--                      ),
--           body    := '{}'::jsonb
--         );
--       $$
--     );
--
--   AUTH (atualizado 2026-08-07): usar x-cron-secret com o valor do edge
--   secret SOLO_HEALTH_CRON_SECRET — não embutir service-role key no
--   cron.job. A key embutida quebra silenciosamente (401) quando as chaves
--   do projeto são rotacionadas, como ocorreu com o job original.
--
--   Verify registration:
--
--     SELECT * FROM cron.job WHERE jobname = 'sprint7_health_tick';
--
--   Verify recent runs:
--
--     SELECT *
--     FROM cron.job_run_details
--     WHERE jobname = 'sprint7_health_tick'
--     ORDER BY start_time DESC
--     LIMIT 5;
--
-- TO DISABLE LATER
--
--     SELECT cron.unschedule('sprint7_health_tick');
--
-- ============================================================================
