// ============================================================================
// Sprint 8 · T6 — start a subscription.
//
// WHAT WAS WRONG (audit item 2): this function wrote
//   subscription_status: 'ACTIVE'
// at index.ts:185, at the moment the subscription was CREATED — before anybody
// paid anything. Access was granted on intent. That single line is the
// pay-nothing-get-everything hole, and it is gone.
//
// NOW: this creates a DRAFT contract, its items, and an OPEN invoice, then a
// charge. The contract becomes 'active' only when asaas-webhook sees a confirmed
// payment. Nothing here grants access.
//
// It also creates a one-off payment rather than an Asaas /subscriptions object:
// the recurring invoice for each period is generated by billing-cron (T7) from
// contract_items at the NEGOTIATED price. An Asaas subscription carries its own
// fixed value and would drift from the contract the moment anything is discounted.
// ============================================================================

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.80.0";
import { createCustomer, createPayment, dueDateIn, getPixQrCode, updateCustomer } from "../_shared/asaas.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const url = Deno.env.get("SUPABASE_URL") ?? "";
    const userClient = createClient(url, Deno.env.get("SUPABASE_ANON_KEY") ?? "", {
      global: { headers: { Authorization: req.headers.get("Authorization")! } },
    });
    const db = createClient(url, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "", {
      auth: { autoRefreshToken: false, persistSession: false },
    });

    const { data: { user }, error: authError } = await userClient.auth.getUser();
    if (authError || !user) return json({ error: "unauthorized" }, 401);

    const body = await req.json().catch(() => ({}));
    const { plano_id, product_id, paymentMethod } = body as {
      plano_id?: number;
      product_id?: string;
      paymentMethod?: string;
    };

    const { data: profile } = await db
      .from("profiles").select("equipe_id, email, nome_completo, telefone")
      .eq("user_id", user.id).maybeSingle();
    if (!profile?.equipe_id) return json({ error: "profile_not_found" }, 404);
    const equipeId = profile.equipe_id as string;

    // --- resolve the plan from the catalog -----------------------------------
    // `plano_id` is the legacy integer from `planos`; the catalog stores it in
    // metadata.legacy_plano_id so old callers keep working until T13.
    let plan;
    if (product_id) {
      const { data } = await db.from("billing_products")
        .select("id, name, list_price, credits_included, kind, active")
        .eq("id", product_id).eq("kind", "plan").maybeSingle();
      plan = data;
    } else if (plano_id != null) {
      const { data } = await db.from("billing_products")
        .select("id, name, list_price, credits_included, kind, active")
        .eq("kind", "plan").eq("code", `plan_${plano_id}`).maybeSingle();
      plan = data;
    } else {
      return json({ error: "product_id_required" }, 400);
    }
    if (!plan || !plan.active) return json({ error: "plan_not_found" }, 404);

    const price = Number(plan.list_price);

    // --- the payer is the team ----------------------------------------------
    const { data: account } = await db
      .from("billing_accounts")
      .select("equipe_id, doc_type, doc_number, legal_name, billing_email, phone, asaas_customer_id")
      .eq("equipe_id", equipeId).maybeSingle();

    if (!account?.doc_number || !account?.doc_type) {
      return json({ error: "billing_account_incomplete" }, 422);
    }

    let customerId = account.asaas_customer_id;
    if (!customerId) {
      const customer = await createCustomer({
        name: account.legal_name ?? profile.nome_completo ?? "Cliente",
        email: account.billing_email ?? profile.email,
        cpfCnpj: account.doc_number,
        phone: account.phone ?? profile.telefone,
      });
      customerId = customer.id;
      await db.from("billing_accounts").update({ asaas_customer_id: customerId }).eq("equipe_id", equipeId);
    } else {
      await updateCustomer(customerId, { cpfCnpj: account.doc_number }).catch((e) =>
        console.error("[subscribe] customer update failed:", e.message)
      );
    }

    // --- contract (draft) ----------------------------------------------------
    // A partial unique index allows only one live contract per team, so reuse an
    // existing draft rather than colliding with it.
    const { data: existing } = await db
      .from("contracts").select("id, status")
      .eq("equipe_id", equipeId).in("status", ["draft", "active", "past_due", "suspended"])
      .maybeSingle();

    let contractId: string;
    if (existing) {
      contractId = existing.id;
      if (existing.status !== "draft") {
        return json({ error: "contract_already_active", contract_id: contractId }, 409);
      }
      await db.from("contract_items").delete().eq("contract_id", contractId);
    } else {
      const { data: created, error } = await db
        .from("contracts").insert({ equipe_id: equipeId, status: "draft" })
        .select("id").single();
      if (error) throw new Error(`contract insert failed: ${error.message}`);
      contractId = created.id;
    }

    await db.from("contract_items").insert({
      contract_id: contractId,
      product_id: plan.id,
      quantity: 1,
      unit_price: price, // catalog price here; a negotiated deal sets its own via provision-tenant
      period: "monthly",
    });

    // --- invoice, then charge ------------------------------------------------
    const { data: invoice, error: invErr } = await db
      .from("invoices")
      .insert({
        equipe_id: equipeId,
        contract_id: contractId,
        kind: "recurring",
        status: "open",
        subtotal: price,
        total: price,
        due_date: dueDateIn(1),
        issued_at: new Date().toISOString(),
      })
      .select("id, number").single();
    if (invErr) throw new Error(`invoice insert failed: ${invErr.message}`);

    await db.from("invoice_items").insert({
      invoice_id: invoice.id,
      product_id: plan.id,
      description: plan.name,
      quantity: 1,
      unit_price: price,
      total: price,
    });

    const payment = await createPayment({
      customer: customerId!,
      billingType: paymentMethod === "PIX" ? "PIX" : "UNDEFINED",
      value: price,
      dueDate: dueDateIn(1),
      description: `${plan.name} — fatura ${invoice.number}`,
      externalReference: `invoice_${invoice.id}`,
    });

    const patch: Record<string, unknown> = {
      asaas_payment_id: payment.id,
      asaas_invoice_url: payment.invoiceUrl ?? null,
    };

    let pixQrCode: string | undefined;
    let pixCopyPaste: string | undefined;
    if (paymentMethod === "PIX") {
      const qr = await getPixQrCode(payment.id);
      pixQrCode = qr.encodedImage;
      pixCopyPaste = qr.payload;
      patch.pix_payload = qr.payload ?? null;
    }
    await db.from("invoices").update(patch).eq("id", invoice.id);

    // NOTE: no write to equipes.subscription_status here, and none to
    // contracts.status. Activation belongs to asaas-webhook alone.
    return json({
      success: true,
      contractId,
      invoiceId: invoice.id,
      invoiceNumber: invoice.number,
      paymentId: payment.id,
      invoiceUrl: payment.invoiceUrl,
      pixQrCode,
      pixCopyPaste,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "unknown error";
    console.error("[subscribe] fatal:", message);
    return json({ error: message }, 500);
  }
});
